apiVersion: v1
kind: Service
metadata:
  name: gateway-yeeter
  namespace: openshift-mtv
  labels:
    app: gateway-yeeter
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: gateway-yeeter-certs
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: gateway-yeeter
