apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gateway-yeeter
  labels:
    app: gateway-yeeter
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
  - name: virt-v2v.gateway.yeet
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: gateway-yeeter
        namespace: openshift-mtv
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        forklift.app: virt-v2v
    failurePolicy: Ignore
    sideEffects: None
    timeoutSeconds: 5
  - name: cdi.gateway.yeet
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        name: gateway-yeeter
        namespace: openshift-mtv
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    namespaceSelector: {}
    objectSelector:
      matchLabels:
        app: containerized-data-importer
    failurePolicy: Ignore
    sideEffects: None
    timeoutSeconds: 5
